

# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun
$lockManager = hyprlock
$fullscreen = fullscreen
$notificationCenter = dunstctl history-pop

# keyboard change
input {
    kb_layout = us,ru
    kb_options = grp:win_space_toggle
    sensitivity = 20
    force_no_accel = 1
    accel_profile = flat
    follow_mouse = 2
    float_switch_override_focus = 0
}

# rules for phpstorm (ctrl + shift + F)
windowrulev = noinitialfocus,class:^(jetbrains-.*),title:^(win.*)

# lockscreen
bind = $mainMod, L, exec, $lockManager

# fullscreen 
bind = SUPER, F, $fullscreen, 0

# alt + tab
bind = ALT, Tab, cyclenext,

# monitors settings 
monitor = eDP-1, 1920x1080@144, 0x0, 1
monitor = HDMI-A-1, 1920x1080@144, 1920x0, 1
monitor = DP-1, 1920x1080@144, 3840x0, 1

# screenshots
bind = , Print, exec, hyprshot -m region --clipboard-only

# notifications
bind = $mainMod, n, exec, $notificationCenter

# music control
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPrev, exec, playerctl previous
bindl = , XF86AudioStop, exec, playerctl stop

# sound and brightness level
bind = ,XF86AudioLowerVolume, exec, pactl -- set-sink-volume 0 -10%
bind = ,XF86AudioRaiseVolume, exec, pactl -- set-sink-volume 0 +10%
bind = ,XF86AudioMute, exec, pactl -- set-sink-mute 0 toggle
bind = ,XF86AudioMicMute, exec, pactl -- set-source-mute 0 toggle
bind = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-
bind = ,XF86MonBrightnessUp, exec, brightnessctl s +10%

# change monitors
bind = $mainMod SHIFT, left, movewindow, mon:l
bind = $mainMod SHIFT, right, movewindow, mon:r
bind = $mainMod SHIFT, up, movewindow, mon:u
bind = $mainMod SHIFT, down, movewindow, mon:d

# wlogout
bind = $mainMod, Escape, exec, ~/.local/lib/hyde/logoutlaunch.sh

# defaults
bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
# bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
